# Generated by Django 5.0.7 on 2024-07-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restorans_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='List',
        ),
    ]
